"""empty message

Revision ID: 07010ff69b64
Revises: 8ab512268491
Create Date: 2020-04-04 18:43:22.168984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07010ff69b64'
down_revision = '8ab512268491'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venue_listing')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venue_listing',
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('upcoming', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('start_time', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], name='venue_listing_artist_id_fkey'),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], name='venue_listing_venue_id_fkey'),
    sa.PrimaryKeyConstraint('venue_id', 'artist_id', name='venue_listing_pkey')
    )
    # ### end Alembic commands ###
