"""empty message

Revision ID: e78e52685bcf
Revises: 07010ff69b64
Create Date: 2020-04-04 19:16:05.964893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e78e52685bcf'
down_revision = '07010ff69b64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('artist_id', sa.Integer(), nullable=True))
    op.add_column('Shows', sa.Column('venue_id', sa.Integer(), nullable=True))
    op.alter_column('Shows', 'start_time',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'Shows', 'Artist', ['artist_id'], ['id'])
    op.create_foreign_key(None, 'Shows', 'Venue', ['venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Shows', type_='foreignkey')
    op.drop_constraint(None, 'Shows', type_='foreignkey')
    op.alter_column('Shows', 'start_time',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('Shows', 'venue_id')
    op.drop_column('Shows', 'artist_id')
    # ### end Alembic commands ###
